import React from 'react';

// Card data array
export const cardData = [
  { id: '1', title: 'Hope', img: require('../assets/cards/1.jpeg') },
  { id: '2', title: 'Love', img: require('../assets/cards/2.jpeg') },
  { id: '3', title: 'Heart', img: require('../assets/cards/3.jpeg') },
  { id: '4', title: 'Esc', img: require('../assets/cards/4.jpeg') },
  { id: '5', title: 'Shoot', img: require('../assets/cards/5.jpeg') },
  { id: '6', title: 'Hit', img: require('../assets/cards/6.jpeg') },
  { id: '7', title: 'No Way', img: require('../assets/cards/7.jpeg') },
  { id: '8', title: 'Moon', img: require('../assets/cards/8.jpeg') },
  { id: '9', title: 'Game', img: require('../assets/cards/9.jpeg') },
  { id: '10', title: 'Song', img: require('../assets/cards/10.jpeg') },
  { id: '11', title: 'Pizza', img: require('../assets/cards/11.jpeg') },
  { id: '12', title: 'Search', img: require('../assets/cards/12.jpeg') },
  { id: '13', title: 'Chase', img: require('../assets/cards/13.jpeg') },
  { id: '14', title: 'Tired', img: require('../assets/cards/14.jpeg') },
  { id: '15', title: 'Finger', img: require('../assets/cards/15.jpeg') },
  { id: '16', title: 'Soul', img: require('../assets/cards/16.jpeg') },
  { id: '17', title: 'Hope', img: require('../assets/cards/17.jpeg') },
  { id: '18', title: 'Cycle', img: require('../assets/cards/18.jpeg') },
  { id: '19', title: 'Xylophone', img: require('../assets/cards/19.jpeg') },
  { id: '20', title: 'Coffee', img: require('../assets/cards/20.jpeg') },
  { id: '21', title: 'AK47', img: require('../assets/cards/21.jpeg') },
  { id: '22', title: 'Man', img: require('../assets/cards/22.jpeg') },
  { id: '23', title: 'Bowling', img: require('../assets/cards/23.jpeg') },
  { id: '24', title: 'USB', img: require('../assets/cards/24.jpeg') },
  { id: '25', title: 'Freedom', img: require('../assets/cards/25.jpeg') },
  { id: '26', title: 'Think', img: require('../assets/cards/26.jpeg') },
  { id: '27', title: 'Hope', img: require('../assets/cards/27.jpeg') },
  { id: '28', title: 'Wait', img: require('../assets/cards/28.jpeg') },
  { id: '29', title: 'Bike', img: require('../assets/cards/29.jpeg') },
  { id: '30', title: 'Spicy', img: require('../assets/cards/30.jpeg') },
  { id: '31', title: 'Love', img: require('../assets/cards/31.jpeg') },
  { id: '32', title: 'Heart', img: require('../assets/cards/32.jpeg') },
  { id: '33', title: 'Esc', img: require('../assets/cards/33.jpeg') },
  { id: '34', title: 'Shoot', img: require('../assets/cards/34.jpeg') },
  { id: '35', title: 'Hit', img: require('../assets/cards/35.jpeg') },
  { id: '36', title: 'No Way', img: require('../assets/cards/36.jpeg') },
  { id: '37', title: 'Moon', img: require('../assets/cards/37.jpeg') },
  { id: '38', title: 'Game', img: require('../assets/cards/38.jpeg') },
  { id: '39', title: 'Song', img: require('../assets/cards/39.jpeg') },
  { id: '40', title: 'Pizza', img: require('../assets/cards/40.jpeg') },
  { id: '41', title: 'Search', img: require('../assets/cards/41.jpeg') },
  { id: '42', title: 'Chase', img: require('../assets/cards/42.jpeg') },
  { id: '43', title: 'Tired', img: require('../assets/cards/43.jpeg') },
  { id: '44', title: 'Finger', img: require('../assets/cards/44.jpeg') },
  { id: '45', title: 'Soul', img: require('../assets/cards/45.jpeg') },
  { id: '46', title: 'Hope', img: require('../assets/cards/46.jpeg') },
  { id: '47', title: 'Cycle', img: require('../assets/cards/47.jpeg') },
  { id: '48', title: 'Xylophone', img: require('../assets/cards/48.jpeg') },
  { id: '49', title: 'Coffee', img: require('../assets/cards/49.jpeg') },
  { id: '50', title: 'AK47', img: require('../assets/cards/50.jpeg') },
  { id: '51', title: 'AK47', img: require('../assets/cards/51.jpeg') },
  { id: '52', title: 'AK47', img: require('../assets/cards/52.jpeg') },
  { id: '53', title: 'AK47', img: require('../assets/cards/53.jpeg') },
  { id: '54', title: 'AK47', img: require('../assets/cards/54.jpeg') },
  { id: '55', title: 'AK47', img: require('../assets/cards/55.jpg') },
  { id: '56', title: 'AK47', img: require('../assets/cards/56.jpeg') },
  { id: '57', title: 'AK47', img: require('../assets/cards/57.jpeg') },
  { id: '58', title: 'AK47', img: require('../assets/cards/58.jpeg') },
  { id: '59', title: 'AK47', img: require('../assets/cards/59.jpeg') },
  { id: '60', title: 'AK47', img: require('../assets/cards/60.jpeg') },
  { id: '61', title: 'AK47', img: require('../assets/cards/61.jpeg') },
  { id: '62', title: 'AK47', img: require('../assets/cards/62.jpeg') },
  { id: '63', title: 'AK47', img: require('../assets/cards/63.jpeg') },
  { id: '64', title: 'AK47', img: require('../assets/cards/64.jpeg') },
  { id: '65', title: 'AK47', img: require('../assets/cards/65.jpeg') },
  { id: '66', title: 'AK47', img: require('../assets/cards/66.jpeg') },
  { id: '67', title: 'AK47', img: require('../assets/cards/67.jpeg') },
];

// Type definition for card data
export interface CardItem {
  id: string;
  title: string;
  img: any; // React Native image source type
}
